package api

type Api interface {
	ServerConnectionIdentity(ServerConnectionIdentityRequest) (ServerConnectionIdentityResponse, error)
	GetWebsocketId(struct{}) (GetWebsocketIdResponse, error)
	PrinterInfo(struct{}) (PrinterInfoResponse, error)

	PrinterEmergencyStop(struct{}) (struct{}, error)
	PrinterRestart(struct{}) (struct{}, error)
	PrinterFirmwareRestart(struct{}) (struct{}, error)
	PrinterObjectsList(struct{}) (PrinterObjectsListResponse, error)
	PrinterObjectsQuery(PrinterObjectsQueryRequest) (PrinterObjectsQueryResponse, error)
	PrinterObjectsSubscribe(PrinterObjectsQueryRequest) (PrinterObjectsQueryResponse, error)
	PrinterQueryEndstopsStatus(struct{}) (PrinterQueryEndstopsStatusResponse, error)
	Serverinfo(struct{}) (ServerInfoResponse, error)
	ServerConfig(struct{}) (ServerConfigResponse, error)
	ServerTemperatureStore(struct{}) (ServerTemperatureStoreResponse, error)
	ServerGCodeStore(ServerGCodeStoreRequest) (ServerGCodeStoreResponse, error)
	ServerRestart(struct{}) (struct{}, error)
	PrinterGCodeScript(PrinterGCodeScriptRequest) (struct{}, error)
	PrinterGCodeHelp(struct{}) (PrinterGCodeHelpResponse, error)
	PrinterPrintStart(PrinterPrintStartRequest) (struct{}, error)
	PrinterPrintPause(struct{}) (struct{}, error)
	PrinterPrintResume(struct{}) (struct{}, error)
	PrinterPrintCancel(struct{}) (struct{}, error)
	MachineSystemInfo(struct{}) (struct{}, error)
	MachineShutdown(struct{}) (struct{}, error)
	MachineReboot(struct{}) (struct{}, error)
	MachineServicesRestart(MachineServicesRestartRequest) (struct{}, error)
	MachineServicesStop(MachineServicesRestartRequest) (struct{}, error)
	MachineServicesStart(MachineServicesRestartRequest) (struct{}, error)
	MachineProcStats(struct{}) (MachineProcStatsResponse, error)
	ServerFilesList(ServerFilesListRequest) (ServerFilesListResponse, error)
}
